version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-here
    volumes:
      - .:/app
      - /app/__pycache__
    restart: unless-stopped
    networks:
      - app-network

  # Opcional: Adicionar um banco de dados PostgreSQL
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: flaskapp
  #     POSTGRES_USER: flaskuser
  #     POSTGRES_PASSWORD: flaskpass
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-network

  # Opcional: Adicionar Redis para cache
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   postgres_data:
